package com.example.devopsagent.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * Root Cause Analysis report generated by the LLM after incident resolution.
 * Sent for human review/editing before being finalized.
 */
@Entity
@Table(name = "rca_reports", indexes = {
        @Index(name = "idx_rca_incident", columnList = "incident_id"),
        @Index(name = "idx_rca_status", columnList = "status"),
        @Index(name = "idx_rca_service", columnList = "service")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RcaReport {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(name = "incident_id", nullable = false)
    private String incidentId;

    private String service;

    @Column(name = "incident_title")
    private String incidentTitle;

    private String severity;

    /** One-paragraph executive summary */
    @Column(length = 2048)
    private String summary;

    /** Chronological event timeline */
    @Column(length = 8192)
    private String timeline;

    /** Identified root cause */
    @Column(name = "root_cause", length = 4096)
    private String rootCause;

    /** Scope and user/business impact */
    @Column(length = 4096)
    private String impact;

    /** Steps taken to resolve */
    @Column(length = 4096)
    private String resolution;

    /** What was learned */
    @Column(name = "lessons_learned", length = 4096)
    private String lessonsLearned;

    /** Action items to prevent recurrence */
    @Column(name = "preventive_measures", length = 4096)
    private String preventiveMeasures;

    /** JSON array of tools involved in the resolution */
    @Column(name = "tools_used", length = 4096)
    private String toolsUsed;

    /** Time to resolve in milliseconds */
    @Column(name = "resolution_time_ms")
    private long resolutionTimeMs;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private RcaStatus status = RcaStatus.GENERATING;

    @Column(name = "generated_at")
    private Instant generatedAt;

    @Column(name = "reviewed_at")
    private Instant reviewedAt;

    @Column(name = "reviewed_by")
    private String reviewedBy;

    /** Reviewer's comments */
    @Column(name = "review_notes", length = 2048)
    private String reviewNotes;

    public enum RcaStatus {
        GENERATING, PENDING_REVIEW, APPROVED, REJECTED
    }

    @PrePersist
    protected void onCreate() {
        if (generatedAt == null) generatedAt = Instant.now();
        if (status == null) status = RcaStatus.GENERATING;
    }
}
